// デモ初期データ
export const INITIAL_EMPLOYEES = [
  // 営業部（正社員・契約社員）
  { id:1,  code:"EMP001", name:"田中 太郎",   nameKana:"タナカ タロウ",     department:"営業部", employmentType:"正社員",   payType:"月給制",   insuranceFlags:{healthInsurance:true, welfarePension:true, employmentInsurance:true},  baseSalary:280000, dailyWage:0, transportAllowance:15000, housingAllowance:20000, otherAllowance:0,    age:42, dependents:2, residentTax:18000, joinDate:"2018-04-01", retireDate:"", hourlyWage:0,    monthlyHours:0,   enabledIncentives:["inc_1","inc_2"] },
  { id:2,  code:"EMP002", name:"鈴木 花子",   nameKana:"スズキ ハナコ",     department:"管理部", employmentType:"正社員",   payType:"月給制",   insuranceFlags:{healthInsurance:true, welfarePension:true, employmentInsurance:true},  baseSalary:240000, dailyWage:0, transportAllowance:12000, housingAllowance:0,     otherAllowance:5000, age:35, dependents:1, residentTax:14000, joinDate:"2020-07-01", retireDate:"", hourlyWage:0,    monthlyHours:0,   enabledIncentives:["inc_3","inc_4"] },
  { id:3,  code:"EMP003", name:"佐藤 次郎",   nameKana:"サトウ ジロウ",     department:"整備部", employmentType:"パート",   payType:"時間給制", insuranceFlags:{healthInsurance:false,welfarePension:false,employmentInsurance:true},  baseSalary:0,      dailyWage:0, transportAllowance:0,     housingAllowance:0,     otherAllowance:0,    age:28, dependents:0, residentTax:0,     joinDate:"2023-01-10", retireDate:"", hourlyWage:1200, monthlyHours:120, enabledIncentives:["inc_2"] },
  { id:4,  code:"EMP004", name:"山田 美咲",   nameKana:"ヤマダ ミサキ",     department:"受付",   employmentType:"契約社員", payType:"月給制",   insuranceFlags:{healthInsurance:true, welfarePension:true, employmentInsurance:true},  baseSalary:210000, dailyWage:0, transportAllowance:10000, housingAllowance:0,     otherAllowance:0,    age:30, dependents:0, residentTax:11000, joinDate:"2022-04-01", retireDate:"", hourlyWage:0,    monthlyHours:0,   enabledIncentives:["inc_1","inc_5"] },
  { id:5,  code:"EMP005", name:"伊藤 健一",   nameKana:"イトウ ケンイチ",   department:"営業部", employmentType:"正社員",   payType:"月給制",   insuranceFlags:{healthInsurance:true, welfarePension:true, employmentInsurance:true},  baseSalary:320000, dailyWage:0, transportAllowance:18000, housingAllowance:20000, otherAllowance:0,    age:45, dependents:3, residentTax:22000, joinDate:"2015-04-01", retireDate:"", hourlyWage:0,    monthlyHours:0,   enabledIncentives:["inc_1","inc_4"] },
  { id:6,  code:"EMP006", name:"渡辺 さくら", nameKana:"ワタナベ サクラ",   department:"営業部", employmentType:"正社員",   payType:"月給制",   insuranceFlags:{healthInsurance:true, welfarePension:true, employmentInsurance:true},  baseSalary:260000, dailyWage:0, transportAllowance:14000, housingAllowance:0,     otherAllowance:0,    age:31, dependents:0, residentTax:15000, joinDate:"2019-10-01", retireDate:"", hourlyWage:0,    monthlyHours:0,   enabledIncentives:["inc_1","inc_2"] },
  { id:7,  code:"EMP007", name:"中村 拓也",   nameKana:"ナカムラ タクヤ",   department:"整備部", employmentType:"正社員",   payType:"日給月給制",insuranceFlags:{healthInsurance:true, welfarePension:true, employmentInsurance:true},  baseSalary:250000, dailyWage:0, transportAllowance:10000, housingAllowance:15000, otherAllowance:0,    age:33, dependents:1, residentTax:13000, joinDate:"2021-04-01", retireDate:"", hourlyWage:0,    monthlyHours:0,   enabledIncentives:["inc_3"] },
  { id:8,  code:"EMP008", name:"小林 直美",   nameKana:"コバヤシ ナオミ",   department:"管理部", employmentType:"正社員",   payType:"月給制",   insuranceFlags:{healthInsurance:true, welfarePension:true, employmentInsurance:true},  baseSalary:230000, dailyWage:0, transportAllowance:8000,  housingAllowance:0,     otherAllowance:3000, age:38, dependents:2, residentTax:12000, joinDate:"2017-07-01", retireDate:"", hourlyWage:0,    monthlyHours:0,   enabledIncentives:["inc_3","inc_4"] },
  { id:9,  code:"EMP009", name:"加藤 雄介",   nameKana:"カトウ ユウスケ",   department:"整備部", employmentType:"正社員",   payType:"日給制",   insuranceFlags:{healthInsurance:true, welfarePension:true, employmentInsurance:true},  baseSalary:0,      dailyWage:12500, transportAllowance:12000, housingAllowance:0, otherAllowance:0,    age:36, dependents:1, residentTax:16000, joinDate:"2016-04-01", retireDate:"", hourlyWage:0,    monthlyHours:0,   enabledIncentives:["inc_3","inc_5"] },
  { id:10, code:"EMP010", name:"吉田 美穂",   nameKana:"ヨシダ ミホ",       department:"受付",   employmentType:"パート",   payType:"時間給制", insuranceFlags:{healthInsurance:false,welfarePension:false,employmentInsurance:true},  baseSalary:0,      dailyWage:0, transportAllowance:0,     housingAllowance:0,     otherAllowance:0,    age:25, dependents:0, residentTax:0,     joinDate:"2023-06-01", retireDate:"", hourlyWage:1100, monthlyHours:100, enabledIncentives:[] },
  { id:11, code:"EMP011", name:"松本 大輔",   nameKana:"マツモト ダイスケ", department:"営業部", employmentType:"正社員",   payType:"月給制",   insuranceFlags:{healthInsurance:true, welfarePension:true, employmentInsurance:true},  baseSalary:295000, dailyWage:0, transportAllowance:16000, housingAllowance:20000, otherAllowance:0,    age:40, dependents:2, residentTax:19000, joinDate:"2014-04-01", retireDate:"", hourlyWage:0,    monthlyHours:0,   enabledIncentives:["inc_1","inc_2"] },
  { id:12, code:"EMP012", name:"井上 恵子",   nameKana:"イノウエ ケイコ",   department:"管理部", employmentType:"契約社員", payType:"月給制",   insuranceFlags:{healthInsurance:true, welfarePension:true, employmentInsurance:true},  baseSalary:200000, dailyWage:0, transportAllowance:9000,  housingAllowance:0,     otherAllowance:0,    age:29, dependents:0, residentTax:10000, joinDate:"2022-10-01", retireDate:"", hourlyWage:0,    monthlyHours:0,   enabledIncentives:["inc_3"] },
  { id:13, code:"EMP013", name:"木村 俊介",   nameKana:"キムラ シュンスケ", department:"整備部", employmentType:"正社員",   payType:"日給月給制",insuranceFlags:{healthInsurance:true, welfarePension:true, employmentInsurance:true},  baseSalary:245000, dailyWage:0, transportAllowance:11000, housingAllowance:0,     otherAllowance:0,    age:27, dependents:0, residentTax:12000, joinDate:"2022-04-01", retireDate:"", hourlyWage:0,    monthlyHours:0,   enabledIncentives:["inc_3"] },
  { id:14, code:"EMP014", name:"林 奈々",     nameKana:"ハヤシ ナナ",       department:"受付",   employmentType:"アルバイト",payType:"時間給制",insuranceFlags:{healthInsurance:false,welfarePension:false,employmentInsurance:true},  baseSalary:0,      dailyWage:0, transportAllowance:0,     housingAllowance:0,     otherAllowance:0,    age:22, dependents:0, residentTax:0,     joinDate:"2024-01-15", retireDate:"", hourlyWage:1050, monthlyHours:80,  enabledIncentives:[] },
  { id:15, code:"EMP015", name:"清水 博之",   nameKana:"シミズ ヒロユキ",   department:"経営",   employmentType:"役員",     payType:"月給制",   insuranceFlags:{healthInsurance:true, welfarePension:true, employmentInsurance:false}, baseSalary:500000, dailyWage:0, transportAllowance:0,     housingAllowance:50000, otherAllowance:0,    age:55, dependents:2, residentTax:45000, joinDate:"2010-01-01", retireDate:"", hourlyWage:0,    monthlyHours:0,   enabledIncentives:["inc_4"] },
  { id:16, code:"EMP016", name:"山口 真理",   nameKana:"ヤマグチ マリ",     department:"営業部", employmentType:"正社員",   payType:"月給制",   insuranceFlags:{healthInsurance:true, welfarePension:true, employmentInsurance:true},  baseSalary:255000, dailyWage:0, transportAllowance:13000, housingAllowance:0,     otherAllowance:0,    age:34, dependents:1, residentTax:14000, joinDate:"2020-04-01", retireDate:"", hourlyWage:0,    monthlyHours:0,   enabledIncentives:["inc_1","inc_2"] },
  { id:17, code:"EMP017", name:"森 隆",       nameKana:"モリ タカシ",       department:"整備部", employmentType:"正社員",   payType:"日給月給制",insuranceFlags:{healthInsurance:true, welfarePension:true, employmentInsurance:true},  baseSalary:260000, dailyWage:0, transportAllowance:10000, housingAllowance:15000, otherAllowance:0,    age:39, dependents:2, residentTax:15000, joinDate:"2018-07-01", retireDate:"", hourlyWage:0,    monthlyHours:0,   enabledIncentives:["inc_3","inc_5"] },
  { id:18, code:"EMP018", name:"池田 朋子",   nameKana:"イケダ トモコ",     department:"管理部", employmentType:"パート",   payType:"時間給制", insuranceFlags:{healthInsurance:true, welfarePension:true, employmentInsurance:true},  baseSalary:0,      dailyWage:0, transportAllowance:0,     housingAllowance:0,     otherAllowance:0,    age:43, dependents:2, residentTax:0,     joinDate:"2021-09-01", retireDate:"", hourlyWage:1300, monthlyHours:140, enabledIncentives:["inc_2"] },
  { id:19, code:"EMP019", name:"橋本 翔太",   nameKana:"ハシモト ショウタ", department:"営業部", employmentType:"正社員",   payType:"月給制",   insuranceFlags:{healthInsurance:true, welfarePension:true, employmentInsurance:true},  baseSalary:235000, dailyWage:0, transportAllowance:12000, housingAllowance:0,     otherAllowance:0,    age:26, dependents:0, residentTax:11000, joinDate:"2023-04-01", retireDate:"", hourlyWage:0,    monthlyHours:0,   enabledIncentives:["inc_1"] },
  { id:20, code:"EMP020", name:"藤田 里奈",   nameKana:"フジタ リナ",       department:"受付",   employmentType:"契約社員", payType:"月給制",   insuranceFlags:{healthInsurance:true, welfarePension:true, employmentInsurance:true},  baseSalary:205000, dailyWage:0, transportAllowance:9000,  housingAllowance:0,     otherAllowance:0,    age:28, dependents:0, residentTax:10000, joinDate:"2023-07-01", retireDate:"", hourlyWage:0,    monthlyHours:0,   enabledIncentives:["inc_2","inc_3"] },
  // 21〜35追加
  { id:21, code:"EMP021", name:"高橋 誠",     nameKana:"タカハシ マコト",   department:"営業部", employmentType:"正社員",   payType:"月給制",   insuranceFlags:{healthInsurance:true, welfarePension:true, employmentInsurance:true},  baseSalary:275000, dailyWage:0, transportAllowance:15000, housingAllowance:0,     otherAllowance:0,    age:37, dependents:1, residentTax:16000, joinDate:"2017-04-01", retireDate:"", hourlyWage:0,    monthlyHours:0,   enabledIncentives:["inc_1","inc_2"] },
  { id:22, code:"EMP022", name:"岡田 幸子",   nameKana:"オカダ サチコ",     department:"管理部", employmentType:"正社員",   payType:"月給制",   insuranceFlags:{healthInsurance:true, welfarePension:true, employmentInsurance:true},  baseSalary:235000, dailyWage:0, transportAllowance:11000, housingAllowance:0,     otherAllowance:0,    age:32, dependents:0, residentTax:13000, joinDate:"2019-04-01", retireDate:"", hourlyWage:0,    monthlyHours:0,   enabledIncentives:["inc_3"] },
  { id:23, code:"EMP023", name:"斎藤 浩二",   nameKana:"サイトウ コウジ",   department:"整備部", employmentType:"正社員",   payType:"日給制",   insuranceFlags:{healthInsurance:true, welfarePension:true, employmentInsurance:true},  baseSalary:0,      dailyWage:13000, transportAllowance:10000, housingAllowance:0, otherAllowance:0,    age:34, dependents:0, residentTax:14000, joinDate:"2020-01-06", retireDate:"", hourlyWage:0,    monthlyHours:0,   enabledIncentives:["inc_3"] },
  { id:24, code:"EMP024", name:"石川 由美",   nameKana:"イシカワ ユミ",     department:"受付",   employmentType:"パート",   payType:"時間給制", insuranceFlags:{healthInsurance:false,welfarePension:false,employmentInsurance:true},  baseSalary:0,      dailyWage:0, transportAllowance:0,     housingAllowance:0,     otherAllowance:0,    age:40, dependents:1, residentTax:0,     joinDate:"2022-06-01", retireDate:"", hourlyWage:1150, monthlyHours:90,  enabledIncentives:[] },
  { id:25, code:"EMP025", name:"前田 健太",   nameKana:"マエダ ケンタ",     department:"営業部", employmentType:"正社員",   payType:"月給制",   insuranceFlags:{healthInsurance:true, welfarePension:true, employmentInsurance:true},  baseSalary:290000, dailyWage:0, transportAllowance:17000, housingAllowance:20000, otherAllowance:0,    age:41, dependents:2, residentTax:19000, joinDate:"2013-04-01", retireDate:"", hourlyWage:0,    monthlyHours:0,   enabledIncentives:["inc_1","inc_4"] },
  { id:26, code:"EMP026", name:"後藤 美樹",   nameKana:"ゴトウ ミキ",       department:"管理部", employmentType:"契約社員", payType:"月給制",   insuranceFlags:{healthInsurance:true, welfarePension:true, employmentInsurance:true},  baseSalary:215000, dailyWage:0, transportAllowance:10000, housingAllowance:0,     otherAllowance:0,    age:27, dependents:0, residentTax:10000, joinDate:"2023-01-10", retireDate:"", hourlyWage:0,    monthlyHours:0,   enabledIncentives:["inc_3"] },
  { id:27, code:"EMP027", name:"長谷川 修",   nameKana:"ハセガワ オサム",   department:"整備部", employmentType:"正社員",   payType:"日給月給制",insuranceFlags:{healthInsurance:true, welfarePension:true, employmentInsurance:true},  baseSalary:255000, dailyWage:0, transportAllowance:12000, housingAllowance:0,     otherAllowance:0,    age:44, dependents:3, residentTax:17000, joinDate:"2012-07-01", retireDate:"", hourlyWage:0,    monthlyHours:0,   enabledIncentives:["inc_3","inc_5"] },
  { id:28, code:"EMP028", name:"村田 彩",     nameKana:"ムラタ アヤ",       department:"受付",   employmentType:"アルバイト",payType:"時間給制",insuranceFlags:{healthInsurance:false,welfarePension:false,employmentInsurance:true},  baseSalary:0,      dailyWage:0, transportAllowance:0,     housingAllowance:0,     otherAllowance:0,    age:20, dependents:0, residentTax:0,     joinDate:"2024-04-01", retireDate:"", hourlyWage:1080, monthlyHours:60,  enabledIncentives:[] },
  { id:29, code:"EMP029", name:"坂本 隆史",   nameKana:"サカモト タカシ",   department:"営業部", employmentType:"正社員",   payType:"月給制",   insuranceFlags:{healthInsurance:true, welfarePension:true, employmentInsurance:true},  baseSalary:265000, dailyWage:0, transportAllowance:14000, housingAllowance:0,     otherAllowance:0,    age:35, dependents:1, residentTax:15000, joinDate:"2018-10-01", retireDate:"", hourlyWage:0,    monthlyHours:0,   enabledIncentives:["inc_1"] },
  { id:30, code:"EMP030", name:"三浦 香織",   nameKana:"ミウラ カオリ",     department:"管理部", employmentType:"正社員",   payType:"月給制",   insuranceFlags:{healthInsurance:true, welfarePension:true, employmentInsurance:true},  baseSalary:225000, dailyWage:0, transportAllowance:9000,  housingAllowance:0,     otherAllowance:0,    age:30, dependents:0, residentTax:12000, joinDate:"2021-04-01", retireDate:"", hourlyWage:0,    monthlyHours:0,   enabledIncentives:["inc_3","inc_4"] },
  { id:31, code:"EMP031", name:"藤井 勇気",   nameKana:"フジイ ユウキ",     department:"整備部", employmentType:"正社員",   payType:"日給制",   insuranceFlags:{healthInsurance:true, welfarePension:true, employmentInsurance:true},  baseSalary:0,      dailyWage:11500, transportAllowance:8000,  housingAllowance:0, otherAllowance:0,    age:29, dependents:0, residentTax:12000, joinDate:"2022-07-01", retireDate:"", hourlyWage:0,    monthlyHours:0,   enabledIncentives:["inc_3"] },
  { id:32, code:"EMP032", name:"西村 律子",   nameKana:"ニシムラ リツコ",   department:"受付",   employmentType:"パート",   payType:"時間給制", insuranceFlags:{healthInsurance:true, welfarePension:true, employmentInsurance:true},  baseSalary:0,      dailyWage:0, transportAllowance:0,     housingAllowance:0,     otherAllowance:0,    age:48, dependents:0, residentTax:0,     joinDate:"2020-03-01", retireDate:"", hourlyWage:1250, monthlyHours:130, enabledIncentives:["inc_2"] },
  { id:33, code:"EMP033", name:"青木 達也",   nameKana:"アオキ タツヤ",     department:"営業部", employmentType:"正社員",   payType:"月給制",   insuranceFlags:{healthInsurance:true, welfarePension:true, employmentInsurance:true},  baseSalary:245000, dailyWage:0, transportAllowance:13000, housingAllowance:0,     otherAllowance:0,    age:28, dependents:0, residentTax:12000, joinDate:"2024-04-01", retireDate:"", hourlyWage:0,    monthlyHours:0,   enabledIncentives:["inc_1"] },
  { id:34, code:"EMP034", name:"福田 真奈美", nameKana:"フクダ マナミ",     department:"管理部", employmentType:"正社員",   payType:"月給制",   insuranceFlags:{healthInsurance:true, welfarePension:true, employmentInsurance:true},  baseSalary:240000, dailyWage:0, transportAllowance:11000, housingAllowance:0,     otherAllowance:0,    age:33, dependents:1, residentTax:13000, joinDate:"2019-07-01", retireDate:"", hourlyWage:0,    monthlyHours:0,   enabledIncentives:["inc_3"] },
  { id:35, code:"EMP035", name:"岩田 光則",   nameKana:"イワタ ミツノリ",   department:"整備部", employmentType:"正社員",   payType:"日給月給制",insuranceFlags:{healthInsurance:true, welfarePension:true, employmentInsurance:true},  baseSalary:270000, dailyWage:0, transportAllowance:12000, housingAllowance:15000, otherAllowance:0,    age:46, dependents:3, residentTax:18000, joinDate:"2011-04-01", retireDate:"", hourlyWage:0,    monthlyHours:0,   enabledIncentives:["inc_3","inc_5"] },
  // 36〜50（退職者3名含む）
  { id:36, code:"EMP036", name:"上田 直人",   nameKana:"ウエダ ナオト",     department:"営業部", employmentType:"正社員",   payType:"月給制",   insuranceFlags:{healthInsurance:true, welfarePension:true, employmentInsurance:true},  baseSalary:268000, dailyWage:0, transportAllowance:14000, housingAllowance:0,     otherAllowance:0,    age:38, dependents:1, residentTax:15000, joinDate:"2017-10-01", retireDate:"", hourlyWage:0,    monthlyHours:0,   enabledIncentives:["inc_1","inc_2"] },
  { id:37, code:"EMP037", name:"内田 優子",   nameKana:"ウチダ ユウコ",     department:"管理部", employmentType:"パート",   payType:"時間給制", insuranceFlags:{healthInsurance:false,welfarePension:false,employmentInsurance:true},  baseSalary:0,      dailyWage:0, transportAllowance:0,     housingAllowance:0,     otherAllowance:0,    age:36, dependents:2, residentTax:0,     joinDate:"2022-01-11", retireDate:"", hourlyWage:1180, monthlyHours:110, enabledIncentives:[] },
  { id:38, code:"EMP038", name:"田村 裕介",   nameKana:"タムラ ユウスケ",   department:"整備部", employmentType:"正社員",   payType:"日給月給制",insuranceFlags:{healthInsurance:true, welfarePension:true, employmentInsurance:true},  baseSalary:248000, dailyWage:0, transportAllowance:10000, housingAllowance:0,     otherAllowance:0,    age:31, dependents:0, residentTax:13000, joinDate:"2021-07-01", retireDate:"", hourlyWage:0,    monthlyHours:0,   enabledIncentives:["inc_3"] },
  { id:39, code:"EMP039", name:"小野 麻衣",   nameKana:"オノ マイ",         department:"受付",   employmentType:"契約社員", payType:"月給制",   insuranceFlags:{healthInsurance:true, welfarePension:true, employmentInsurance:true},  baseSalary:208000, dailyWage:0, transportAllowance:9000,  housingAllowance:0,     otherAllowance:0,    age:26, dependents:0, residentTax:10000, joinDate:"2023-10-01", retireDate:"", hourlyWage:0,    monthlyHours:0,   enabledIncentives:["inc_2"] },
  { id:40, code:"EMP040", name:"川口 翼",     nameKana:"カワグチ ツバサ",   department:"営業部", employmentType:"正社員",   payType:"月給制",   insuranceFlags:{healthInsurance:true, welfarePension:true, employmentInsurance:true},  baseSalary:282000, dailyWage:0, transportAllowance:16000, housingAllowance:20000, otherAllowance:0,    age:43, dependents:2, residentTax:18000, joinDate:"2016-04-01", retireDate:"", hourlyWage:0,    monthlyHours:0,   enabledIncentives:["inc_1","inc_4"] },
  { id:41, code:"EMP041", name:"竹内 文子",   nameKana:"タケウチ フミコ",   department:"管理部", employmentType:"正社員",   payType:"月給制",   insuranceFlags:{healthInsurance:true, welfarePension:true, employmentInsurance:true},  baseSalary:228000, dailyWage:0, transportAllowance:10000, housingAllowance:0,     otherAllowance:0,    age:29, dependents:0, residentTax:12000, joinDate:"2022-04-01", retireDate:"", hourlyWage:0,    monthlyHours:0,   enabledIncentives:["inc_3"] },
  { id:42, code:"EMP042", name:"原 大地",     nameKana:"ハラ ダイチ",       department:"整備部", employmentType:"正社員",   payType:"日給制",   insuranceFlags:{healthInsurance:true, welfarePension:true, employmentInsurance:true},  baseSalary:0,      dailyWage:12000, transportAllowance:9000,  housingAllowance:0, otherAllowance:0,    age:32, dependents:1, residentTax:13000, joinDate:"2020-10-01", retireDate:"", hourlyWage:0,    monthlyHours:0,   enabledIncentives:["inc_3"] },
  { id:43, code:"EMP043", name:"杉山 智子",   nameKana:"スギヤマ トモコ",   department:"受付",   employmentType:"アルバイト",payType:"時間給制",insuranceFlags:{healthInsurance:false,welfarePension:false,employmentInsurance:true},  baseSalary:0,      dailyWage:0, transportAllowance:0,     housingAllowance:0,     otherAllowance:0,    age:21, dependents:0, residentTax:0,     joinDate:"2024-02-01", retireDate:"", hourlyWage:1060, monthlyHours:70,  enabledIncentives:[] },
  { id:44, code:"EMP044", name:"横山 大介",   nameKana:"ヨコヤマ ダイスケ", department:"営業部", employmentType:"正社員",   payType:"月給制",   insuranceFlags:{healthInsurance:true, welfarePension:true, employmentInsurance:true},  baseSalary:258000, dailyWage:0, transportAllowance:13000, housingAllowance:0,     otherAllowance:0,    age:36, dependents:1, residentTax:14000, joinDate:"2018-04-01", retireDate:"", hourlyWage:0,    monthlyHours:0,   enabledIncentives:["inc_1"] },
  { id:45, code:"EMP045", name:"宮崎 千尋",   nameKana:"ミヤザキ チヒロ",   department:"管理部", employmentType:"正社員",   payType:"月給制",   insuranceFlags:{healthInsurance:true, welfarePension:true, employmentInsurance:true},  baseSalary:232000, dailyWage:0, transportAllowance:10000, housingAllowance:0,     otherAllowance:0,    age:31, dependents:0, residentTax:12000, joinDate:"2020-07-01", retireDate:"", hourlyWage:0,    monthlyHours:0,   enabledIncentives:["inc_3","inc_4"] },
  { id:46, code:"EMP046", name:"和田 信也",   nameKana:"ワダ ノブヤ",       department:"整備部", employmentType:"正社員",   payType:"日給月給制",insuranceFlags:{healthInsurance:true, welfarePension:true, employmentInsurance:true},  baseSalary:252000, dailyWage:0, transportAllowance:11000, housingAllowance:0,     otherAllowance:0,    age:35, dependents:2, residentTax:14000, joinDate:"2019-01-07", retireDate:"", hourlyWage:0,    monthlyHours:0,   enabledIncentives:["inc_3","inc_5"] },
  { id:47, code:"EMP047", name:"石井 京子",   nameKana:"イシイ キョウコ",   department:"受付",   employmentType:"パート",   payType:"時間給制", insuranceFlags:{healthInsurance:false,welfarePension:false,employmentInsurance:true},  baseSalary:0,      dailyWage:0, transportAllowance:0,     housingAllowance:0,     otherAllowance:0,    age:44, dependents:1, residentTax:0,     joinDate:"2021-11-01", retireDate:"", hourlyWage:1120, monthlyHours:95,  enabledIncentives:[] },
  { id:48, code:"EMP048", name:"大野 剛",     nameKana:"オオノ タケシ",     department:"営業部", employmentType:"正社員",   payType:"月給制",   insuranceFlags:{healthInsurance:true, welfarePension:true, employmentInsurance:true},  baseSalary:272000, dailyWage:0, transportAllowance:15000, housingAllowance:0,     otherAllowance:0,    age:39, dependents:1, residentTax:16000, joinDate:"2016-10-01", retireDate:"", hourlyWage:0,    monthlyHours:0,   enabledIncentives:["inc_1","inc_2"] },
  // 退職者3名
  { id:49, code:"EMP049", name:"吉川 浩",     nameKana:"ヨシカワ ヒロシ",   department:"営業部", employmentType:"正社員",   payType:"月給制",   insuranceFlags:{healthInsurance:true, welfarePension:true, employmentInsurance:true},  baseSalary:265000, dailyWage:0, transportAllowance:14000, housingAllowance:0,     otherAllowance:0,    age:52, dependents:2, residentTax:20000, joinDate:"2008-04-01", retireDate:"2024-03-31", hourlyWage:0,    monthlyHours:0,   enabledIncentives:[] },
  { id:50, code:"EMP050", name:"中島 美幸",   nameKana:"ナカジマ ミユキ",   department:"管理部", employmentType:"正社員",   payType:"月給制",   insuranceFlags:{healthInsurance:true, welfarePension:true, employmentInsurance:true},  baseSalary:218000, dailyWage:0, transportAllowance:9000,  housingAllowance:0,     otherAllowance:0,    age:34, dependents:1, residentTax:11000, joinDate:"2019-04-01", retireDate:"2024-05-31", hourlyWage:0,    monthlyHours:0,   enabledIncentives:[] },
];

export const INITIAL_ATTENDANCE = {
  "2024-06": {
    1:  { workDays:20, absentDays:0, paidLeaveDays:0, scheduledHours:160, actualHours:168, overtime:8,  lateNight:0, holiday:0 },
    2:  { workDays:20, absentDays:0, paidLeaveDays:0, scheduledHours:160, actualHours:163, overtime:3,  lateNight:0, holiday:0 },
    3:  { workDays:18, absentDays:0, paidLeaveDays:0, scheduledHours:160, actualHours:144, overtime:0,  lateNight:0, holiday:0 },
    4:  { workDays:20, absentDays:0, paidLeaveDays:0, scheduledHours:160, actualHours:160, overtime:0,  lateNight:0, holiday:0 },
    5:  { workDays:20, absentDays:0, paidLeaveDays:0, scheduledHours:160, actualHours:175, overtime:12, lateNight:3, holiday:0 },
    6:  { workDays:19, absentDays:1, paidLeaveDays:0, scheduledHours:160, actualHours:155, overtime:5,  lateNight:0, holiday:0 },
    7:  { workDays:20, absentDays:0, paidLeaveDays:0, scheduledHours:160, actualHours:165, overtime:5,  lateNight:0, holiday:8 },
    8:  { workDays:20, absentDays:0, paidLeaveDays:0, scheduledHours:160, actualHours:162, overtime:2,  lateNight:0, holiday:0 },
    9:  { workDays:20, absentDays:0, paidLeaveDays:0, scheduledHours:160, actualHours:170, overtime:10, lateNight:0, holiday:0 },
    10: { workDays:15, absentDays:0, paidLeaveDays:0, scheduledHours:160, actualHours:100, overtime:0,  lateNight:0, holiday:0 },
    11: { workDays:20, absentDays:0, paidLeaveDays:0, scheduledHours:160, actualHours:168, overtime:8,  lateNight:2, holiday:0 },
    12: { workDays:20, absentDays:0, paidLeaveDays:0, scheduledHours:160, actualHours:160, overtime:0,  lateNight:0, holiday:0 },
    13: { workDays:20, absentDays:0, paidLeaveDays:0, scheduledHours:160, actualHours:164, overtime:4,  lateNight:0, holiday:0 },
    14: { workDays:12, absentDays:0, paidLeaveDays:0, scheduledHours:160, actualHours:80,  overtime:0,  lateNight:0, holiday:0 },
    15: { workDays:20, absentDays:0, paidLeaveDays:0, scheduledHours:160, actualHours:160, overtime:0,  lateNight:0, holiday:0 },
    16: { workDays:20, absentDays:0, paidLeaveDays:0, scheduledHours:160, actualHours:166, overtime:6,  lateNight:0, holiday:0 },
    17: { workDays:20, absentDays:0, paidLeaveDays:0, scheduledHours:160, actualHours:167, overtime:7,  lateNight:0, holiday:8 },
    18: { workDays:18, absentDays:0, paidLeaveDays:0, scheduledHours:160, actualHours:140, overtime:0,  lateNight:0, holiday:0 },
    19: { workDays:20, absentDays:0, paidLeaveDays:0, scheduledHours:160, actualHours:162, overtime:2,  lateNight:0, holiday:0 },
    20: { workDays:20, absentDays:0, paidLeaveDays:0, scheduledHours:160, actualHours:161, overtime:1,  lateNight:0, holiday:0 },
  }
};

// ============================================================
// MAIN APP
// ============================================================

export const INITIAL_BONUS = {
  "2024-06": { payDate:"2024-06-10", data:{ 1:{bonus:300000}, 5:{bonus:350000}, 11:{bonus:280000}, 15:{bonus:600000}, 25:{bonus:320000} } },
  "2024-12": { payDate:"2024-12-10", data:{ 1:{bonus:320000}, 5:{bonus:380000}, 11:{bonus:300000}, 15:{bonus:650000}, 25:{bonus:340000} } },
};
