// スタイル定義
const S = {
  root:{display:"flex",minHeight:"100vh",background:"#f4f6fb",fontFamily:"'Noto Sans JP','Hiragino Kaku Gothic ProN',sans-serif",position:"relative"},
  mobileOverlay:{position:"fixed",inset:0,background:"rgba(0,0,0,0.5)",zIndex:99},
  mainWrap:{flex:1,display:"flex",flexDirection:"column",minWidth:0,overflow:"hidden"},
  mobileHeader:{display:"flex",alignItems:"center",gap:12,padding:"12px 16px",background:"#1a1a2e",position:"sticky",top:0,zIndex:50},
  hamburger:{background:"none",border:"none",cursor:"pointer",display:"flex",flexDirection:"column",gap:5,padding:4},
  hamLine:{display:"block",width:22,height:2,background:"white",borderRadius:2},
  mobileTitle:{color:"white",fontWeight:800,fontSize:15,flex:1},
  mobileTabLabel:{color:"#aaa",fontSize:12,whiteSpace:"nowrap"},
  sidebar:{width:220,background:"#1a1a2e",display:"flex",flexDirection:"column",padding:"20px 12px",gap:2,minHeight:"100vh",flexShrink:0},
  sidebarLogo:{display:"flex",alignItems:"center",gap:10,marginBottom:16,padding:"0 4px"},
  logoMark:{width:36,height:36,borderRadius:10,background:"linear-gradient(135deg,#6c63ff,#00c9a7)",display:"flex",alignItems:"center",justifyContent:"center",fontSize:16,fontWeight:900,color:"white"},
  logoTitle:{color:"white",fontWeight:800,fontSize:16},
  logoSub:{color:"#888",fontSize:10},
  companyBadge:{background:"#ffffff15",color:"#ccc",fontSize:10,padding:"6px 10px",borderRadius:6,marginBottom:10,lineHeight:1.4},
  navBtn:{display:"flex",alignItems:"center",gap:8,padding:"8px 12px",borderRadius:8,border:"none",background:"transparent",color:"#aaa",fontSize:12,cursor:"pointer",textAlign:"left",width:"100%"},
  navBtnActive:{background:"#ffffff15",color:"white",fontWeight:600},
  logoutBtn:{padding:"8px 12px",borderRadius:8,border:"1px solid #333",background:"transparent",color:"#888",fontSize:12,cursor:"pointer",marginTop:8},
  main:{flex:1,overflow:"auto"},
  page:{padding:24,maxWidth:1200},
  pageHeader:{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:20,flexWrap:"wrap",gap:10},
  pageTitle:{fontSize:20,fontWeight:800,color:"#1a1a2e",margin:0},
  statsGrid:{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(190px,1fr))",gap:12,marginBottom:20},
  statCard:{background:"white",borderRadius:12,padding:"14px 16px",borderTop:"4px solid #6c63ff",boxShadow:"0 2px 8px rgba(0,0,0,0.06)"},
  statValue:{fontSize:20,fontWeight:800},
  statLabel:{fontSize:12,color:"#444",marginTop:4,fontWeight:600},
  statSub:{fontSize:11,color:"#aaa",marginTop:2},
  twoCol:{display:"grid",gridTemplateColumns:"1fr 1fr",gap:16},
  card:{background:"white",borderRadius:12,padding:"16px 18px",boxShadow:"0 2px 8px rgba(0,0,0,0.06)"},
  cardTitle:{fontSize:13,fontWeight:700,color:"#1a1a2e",marginBottom:12,marginTop:0},
  barRow:{display:"flex",alignItems:"center",gap:8,marginBottom:8},
  barLabel:{fontSize:12,color:"#555",width:56,flexShrink:0},
  barTrack:{flex:1,height:8,background:"#f0f0f0",borderRadius:4,overflow:"hidden"},
  barFill:{height:"100%",background:"linear-gradient(90deg,#6c63ff,#00c9a7)",borderRadius:4},
  barCnt:{fontSize:12,color:"#888",width:28,textAlign:"right"},
  tableWrap:{background:"white",borderRadius:12,boxShadow:"0 2px 8px rgba(0,0,0,0.06)",overflow:"auto"},
  table:{width:"100%",borderCollapse:"collapse"},
  th:{background:"#1a1a2e",color:"white",padding:"10px 12px",fontSize:12,textAlign:"left",whiteSpace:"nowrap"},
  tr:{borderBottom:"1px solid #f0f0f0"},
  td:{padding:"10px 12px",fontSize:13,color:"#333"},
  deptBadge:{display:"inline-block",padding:"2px 8px",borderRadius:20,background:"#e8f4fd",color:"#1a6db8",fontSize:11,fontWeight:600},
  typeBadge:{display:"inline-block",padding:"2px 8px",borderRadius:20,background:"#f0f0f0",color:"#666",fontSize:11},
  incBadge:{display:"inline-block",padding:"2px 6px",borderRadius:4,background:"#f0edff",color:"#6c63ff",fontSize:10,fontWeight:600},
  masterTag:{display:"flex",alignItems:"center",gap:6,padding:"6px 12px",borderRadius:20,background:"#f0edff",color:"#6c63ff",fontSize:12,fontWeight:600},
  tagDelete:{background:"none",border:"none",color:"#aaa",cursor:"pointer",fontSize:14,padding:"0 2px",lineHeight:1},
  incToggle:{display:"inline-block",padding:"5px 12px",borderRadius:20,fontSize:12,fontWeight:600,transition:"all 0.15s"},
  editBtn:{padding:"4px 10px",marginRight:4,borderRadius:6,border:"1px solid #6c63ff",background:"white",color:"#6c63ff",fontSize:12,cursor:"pointer"},
  deleteBtn:{padding:"4px 10px",borderRadius:6,border:"1px solid #fc5c65",background:"white",color:"#fc5c65",fontSize:12,cursor:"pointer"},
  primaryBtn:{padding:"8px 16px",borderRadius:8,border:"none",background:"linear-gradient(135deg,#6c63ff,#4ecdc4)",color:"white",fontSize:13,fontWeight:700,cursor:"pointer",whiteSpace:"nowrap"},
  secondaryBtn:{padding:"8px 14px",borderRadius:8,border:"1px solid #6c63ff",background:"white",color:"#6c63ff",fontSize:13,fontWeight:600,cursor:"pointer",whiteSpace:"nowrap"},
  cancelBtn:{padding:"8px 16px",borderRadius:8,border:"1px solid #ddd",background:"white",color:"#666",fontSize:13,cursor:"pointer"},
  searchInput:{padding:"8px 12px",borderRadius:8,border:"1px solid #ddd",fontSize:13,outline:"none",minWidth:160},
  formGrid:{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"10px 16px"},
  formRow:{display:"flex",flexDirection:"column",gap:4},
  formLabel:{fontSize:11,color:"#666",fontWeight:600},
  formInput:{padding:"7px 10px",borderRadius:7,border:"1px solid #ddd",fontSize:13,outline:"none"},
  modalOverlay:{position:"fixed",inset:0,background:"rgba(0,0,0,0.5)",display:"flex",alignItems:"center",justifyContent:"center",zIndex:1000},
  modal:{background:"white",borderRadius:14,padding:24,width:540,maxHeight:"90vh",overflow:"auto",boxShadow:"0 20px 60px rgba(0,0,0,0.3)"},
  modalTitle:{fontSize:18,fontWeight:800,marginBottom:18,marginTop:0,color:"#1a1a2e"},
  payslipCard:{background:"white",borderRadius:14,boxShadow:"0 4px 16px rgba(0,0,0,0.08)",overflow:"hidden",maxWidth:720},
  payslipHeader:{background:"#1a1a2e",color:"white",padding:"20px 24px",display:"flex",justifyContent:"space-between",alignItems:"flex-end"},
  payslipCompany:{fontSize:11,color:"#aaa",marginBottom:4},
  payslipTitle:{fontSize:20,fontWeight:800,letterSpacing:"0.2em"},
  payslipMeta:{textAlign:"right"},
  payslipMonth:{fontSize:11,color:"#aaa"},
  payslipName:{fontSize:16,fontWeight:700},
  payslipBody:{display:"grid",gridTemplateColumns:"1fr 1fr"},
  payslipSection:{padding:"16px 20px",borderRight:"1px solid #f0f0f0"},
  sectionHeader:{fontSize:11,fontWeight:800,color:"#6c63ff",letterSpacing:"0.15em",borderBottom:"2px solid #6c63ff",paddingBottom:6,marginBottom:10},
  payslipRow:{display:"flex",justifyContent:"space-between",padding:"5px 0",borderBottom:"1px dotted #eee"},
  payslipRowLabel:{fontSize:12,color:"#555"},
  payslipRowValue:{fontSize:13,fontWeight:600},
  netSalaryBox:{background:"linear-gradient(135deg,#1a1a2e,#2d2d5e)",color:"white",padding:"16px 24px",display:"flex",justifyContent:"space-between",alignItems:"center"},
  netLabel:{fontSize:13,color:"#aaa"},
  netValue:{fontSize:26,fontWeight:900,color:"#00c9a7"},
  loginBg:{minHeight:"100vh",background:"linear-gradient(135deg,#1a1a2e 0%,#2d2d5e 50%,#1a1a2e 100%)",display:"flex",alignItems:"center",justifyContent:"center"},
  loginCard:{background:"white",borderRadius:20,padding:"40px 36px",width:360,boxShadow:"0 30px 80px rgba(0,0,0,0.4)"},
  loginLogo:{width:56,height:56,borderRadius:16,background:"linear-gradient(135deg,#6c63ff,#00c9a7)",display:"flex",alignItems:"center",justifyContent:"center",fontSize:22,fontWeight:900,color:"white",margin:"0 auto 12px"},
  loginTitle:{textAlign:"center",fontSize:24,fontWeight:900,color:"#1a1a2e",margin:"0 0 4px"},
  loginSub:{textAlign:"center",color:"#888",fontSize:12,marginBottom:24},
  loginField:{marginBottom:14},
  loginLabel:{display:"block",fontSize:12,fontWeight:600,color:"#555",marginBottom:4},
  loginInput:{width:"100%",padding:"10px 12px",borderRadius:10,border:"1px solid #ddd",fontSize:14,outline:"none",boxSizing:"border-box"},
  loginError:{color:"#fc5c65",fontSize:12,marginBottom:10,textAlign:"center"},
  loginBtn:{width:"100%",padding:12,borderRadius:10,border:"none",background:"linear-gradient(135deg,#6c63ff,#00c9a7)",color:"white",fontSize:15,fontWeight:800,cursor:"pointer",marginBottom:16},
  loginHint:{textAlign:"center",fontSize:11,color:"#aaa",lineHeight:1.8},
};

// ============================================================
// YEAR END ADJUSTMENT TAB

export default S;
